/********************************************************************
* JetColor_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JetColor_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableJetColor_dict();
extern void G__cpp_setup_inheritanceJetColor_dict();
extern void G__cpp_setup_typetableJetColor_dict();
extern void G__cpp_setup_memvarJetColor_dict();
extern void G__cpp_setup_globalJetColor_dict();
extern void G__cpp_setup_memfuncJetColor_dict();
extern void G__cpp_setup_funcJetColor_dict();
extern void G__set_cpp_environmentJetColor_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JetColor_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__JetColor_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__JetColor_dictLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JetColor_dictLN_string;
extern G__linked_taginfo G__JetColor_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JetColor_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JetColor_dictLN_pairlEstringcOstringgR;

/* STUB derived class for protected member access */
typedef vector<float,allocator<float> > G__vectorlEfloatcOallocatorlEfloatgRsPgR;
typedef pair<string,string> G__pairlEstringcOstringgR;
